apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  labels:
    app:  backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app:  backend
    spec:
      containers:
      - name:  backend
        image:  teslalord/backend:v1
        env:
        - name: DB_HOST
          value: "18.221.96.176"
        ports:
        - containerPort:  8001
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - name: backend
    port: 8001
    targetPort: 8001