apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "backend"
  namespace: ms
  labels:
    app:  "backend"
spec:
  selector:
    matchLabels:
      app: "backend"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  "backend"
    spec:
      containers:
      - name:  "backend"
        image:  teslalord/backend:v1
        ports:
        - containerPort:  8001
          name:  "backend"


---

apiVersion: v1
kind: Service
metadata:
  name: "backend"
  namespace: default
spec:
  selector:
    app: "backend"
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: "backend"
    port: 8001
    targetPort: 8001