apiVersion: apps/v1
kind: Deployment
metadata:
  name:  security
  labels:
    app:  security
spec:
  selector:
    matchLabels:
      app: security
  replicas: 2
  template:
    metadata:
      labels:
        app:  security
    spec:
      containers:
      - name:  security
        image:  teslalord/security:v1
        env:
        - name: DB_HOST
          value: "18.221.96.176"
        - name: HOST
          value: "34.152.35.74"
        ports:
        - containerPort:  8000
---

apiVersion: v1
kind: Service
metadata:
  name: security
  namespace: default
spec:
  selector:
    app: security
  type: LoadBalancer
  ports:
  - name: security
    port: 8000
    targetPort: 8000