apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
  labels:
    app: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security 
    spec:
      containers:
      - name: securityserver
        image: teslalord/security:v1
        env:
        - name: DB_HOST
          value: "10.104.67.174"
        - name: HOST
          value: "10.98.156.20"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: security 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31111